### ISSUE TITLE
[WIP] Please create unifi user, and chown -R unifi /var/lib/unifi /var/log/unifi /var/run/unifi 

### ISSUE THREAD

**Issue by IdleStep** [jcberthon/unifi-docker#5]
Similar to issue https://github.com/jcberthon/unifi-docker/issues/2 there is an issue when creating Kubernetes containers that volumes are created with root ownership https://github.com/kubernetes/kubernetes/issues/2630 . While the runtime does appear to be able to write into the volume without issue, the [unifi.init](https://github.com/jcberthon/unifi-docker/blob/master/unifi.init) script detects that the folder has UID/GID ownership of 0 . Commenting out that check to bypass creates a stateful container that persists through deletions.

**Comment by IdleStep** [comment]
This being a Docker image and docker-compose repository it wasn't right to post this issue here. Closing.

**Comment by jcberthon** [comment]
Thank none-the-less for posting this issue. I might consider making this project Kubernetes ready as well, but currently I'm missing available time.
